name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gianlucabinetti
          outputs: |
            github-snake.svg
            github-snake-dark.svg
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Generate snake animation'
          branch: main
          file_pattern: '*.svg'
